name: CI checks
on:
  pull_request:
    branches: main
  schedule:
    # Run at 8 AM UTC daily
    - cron: "0 8 * * *"

jobs:
  trunk_check:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - uses: actions/checkout@v4
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
